export interface vendor {
  storeName: string;
  email: string;
  userName: string;
  address1: string;
  address2: string;
  country: string;
  city: string;
  state: string;
  postcode?: string;
  paystackRecipientCode: string;
  bankAccount: {};
  storePhone?: string;
  otpCode: string | null;
  otpExpires: Date | null;
  pendingEmail?: string;
  password: string;
  storeType: "Starter" | "Shelf" | "Counter" | "Shop";
  avatar: string;
  bio: string;
  businessLogo: string;
  refreshToken: string;
  businessDescription?: string;
  businessVideo?: string;
  businessHistory?: string;
  businessWorkflow?: string;
  workTools?: string[];
  isBlocked?: string;
  followers: {}[];
  orders: {}[];
  my_bought_products_orders: {}[];
  following: {}[];
  customers: {}[];
  payments: {}[];
  communities: {}[];
  products: {}[];
  communityPosts: {}[];
  craftCategories: string[];
  verificationStatus: "Approved" | "Rejected" | "Pending";
  createdAt: Date;
  emailSent: boolean;
  notifications: {}[];
  returnPolicy: string | null;
  returnpolicyverified: "Approved" | "Rejected" | "Pending";
  kycDocuments: {} | null;
  kycStatus: "Pending" | "Processing" | "Approved" | "Rejected";
  kycSubmittedAt: Date;
  kycReviewedAt: Date;
  subscription: {
    currentPlan: "Starter" | "Shelf" | "Counter" | "Shop";
    billingCycle: "Monthly" | "Quarterly" | "HalfYearly" | "Yearly";
    status: "Active" | "Expired" | "Pending";
    startDate: Date | null;
    expiryDate: Date | null;
    lastPaymentReference?: string;
    // Subscription reminder tracking
    lastExpiryReminderSent?: Date;
    lastSuspendedReminderSent?: Date;
    suspensionStartDate?: Date;
    deletionStage?: number;
    originalProductCount?: number;
  };
}
